export const GAME_CONSTANTS = {
  COST_GROWTH_FACTOR: 1.5,
  BUILD_TIME_GROWTH_FACTOR: 1.25,
  BASE_BUILD_TIME_SECONDS: 20,
  BASE_RESEARCH_COST_MANA: 100,
  RESEARCH_GROWTH_FACTOR: 1.6,
  CHUNK_SIZE: 40,
  WORLD_SIZE: 40,
  COUNTER_BONUS: 1.25,
};
